name: tests

on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'yngvem'
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python with TKinter and a virtual X11 frame buffer
        run: |
          sudo apt-get update
          sudo apt-get install tk-dev python3-tk python3 python3-pip
          sudo apt-get install xvfb
      - name: install build dependencies
        run: |
          python -m pip install --upgrade pip wheel hatch ruff black pytest
      - name: run tests and linter
        run: |
          # Start virtual display driver
          export DISPLAY=:12
          Xvfb $DISPLAY -screen 0 1920x1080x24 2>/tmp/Xvfb.log & sleep 1
          # Run tests and linter
          python -m ruff .
          python -m black --check .
          python -m pytest
